version: '3.8'

services:

  backend:
    image: preran1966/springboot-ecommerce-backend:v1
    container_name: backend-container
    ports:
      - "8081:8081"

  frontend:
    image: preran1966/react-ecommerce-frontend:v4
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend