server {                                      # define nginx web server configuration

    listen 80;                               # nginx listens on port 80

    location / {                             # handle all incoming routes/URLs

        root /usr/share/nginx/html;          # static frontend files location

        index index.html;                    # default file to serve

        try_files $uri /index.html;          # if route/file not found, serve index.html so React Router handles routing
    }
}
